module Docscribe
  module Types
    module Sorbet
      class BaseProvider
        @collapse_generics: bool

        @index: Hash[ [ String, Symbol, Symbol ], Docscribe::Types::MethodSignature ]

        @warned: bool

        def initialize: (?collapse_generics: bool) -> void

        def signature_for: (container: String, scope: Symbol, name: (Symbol | String)) -> (Docscribe::Types::MethodSignature | nil)

        private

        def load_from_string: (String source, label: String) -> void

        def index_decls: (Array[untyped] decls) -> void

        def process_method_member: (String container, untyped member) -> void

        def method_definition_member?: (untyped member) -> bool

        def build_signature: (::RBS::Types::Function func) -> Docscribe::Types::MethodSignature

        def build_param_types: (::RBS::Types::Function func) -> Hash[String, String]

        def add_keywords!: (Hash[String, String] param_types, Hash[Symbol, untyped] keywords) -> void

        def add_positionals!: (Hash[String, String] param_types, Array[untyped] list) -> void

        def build_rest_positional: (::RBS::Types::Function func) -> (Docscribe::Types::RestPositional | nil)

        def build_rest_keywords: (::RBS::Types::Function func) -> (Docscribe::Types::RestKeywords | nil)

        def format_type: (untyped type) -> String

        def normalize_container: (String name) -> String

        def warn_once: (String msg) -> void
      end
    end
  end
end
