module Docscribe
  module Types
    module Sorbet
      class SourceProvider < BaseProvider
        def initialize: (source: String, file: String, ?collapse_generics: bool) -> void
      end
    end
  end
end
