# frozen_string_literal: true

module Docscribe
  module InlineRewriter
    module DocBlock
      module_function

      Entry = Struct.new(
        :kind,         # :tag or :other
        :tag,          # "param", "return", etc.
        :lines,        # Array<String>
        :subject,      # param name for @param
        :option_owner, # owner name for @option
        :generated,    # whether this entry was generated by Docscribe
        :index,        # stable original order
        keyword_init: true
      )

      # Merge existing block lines with generated missing tag lines.
      #
      # Existing lines are preserved exactly. Only generated lines are new.
      #
      # @param existing_lines [Array<String>]
      # @param missing_lines [Array<String>]
      # @param sort_tags [Boolean]
      # @param tag_order [Array<String>]
      # @return [Array<String>]
      def merge(existing_lines, missing_lines:, sort_tags:, tag_order:)
        existing_entries = parse(existing_lines, tag_order: tag_order)
        missing_entries = parse_generated(missing_lines, tag_order: tag_order)

        entries = existing_entries + missing_entries
        entries = sort(entries, tag_order: tag_order) if sort_tags

        render(entries)
      end

      # Parse generated missing tag lines as generated entries.
      #
      # @param lines [Array<String>]
      # @param tag_order [Array<String>]
      # @return [Array<Entry>]
      def parse_generated(lines, tag_order:)
        parse(lines, tag_order: tag_order).map do |entry|
          entry.generated = true if entry.kind == :tag
          entry
        end
      end

      # Parse comment block lines into entries.
      #
      # Only tags listed in tag_order are sortable tags.
      # Other top-level @tags are treated as boundaries / plain entries.
      #
      # @param lines [Array<String>]
      # @param tag_order [Array<String>]
      # @return [Array<Entry>]
      def parse(lines, tag_order:)
        sortable_tags = normalized_tag_order(tag_order)
        entries = []
        i = 0
        index = 0

        while i < lines.length
          line = lines[i]

          if sortable_top_level_tag_line?(line, sortable_tags)
            entry, i = consume_tag_entry(lines, i, index: index, sortable_tags: sortable_tags)
            entries << entry
          else
            entries << Entry.new(
              kind: :other,
              lines: [line],
              generated: false,
              index: index
            )
            i += 1
          end

          index += 1
        end

        entries
      end

      # Sort only inside contiguous tag runs.
      #
      # @param entries [Array<Entry>]
      # @param tag_order [Array<String>]
      # @return [Array<Entry>]
      def sort(entries, tag_order:)
        out = []
        priority = build_priority(tag_order)
        i = 0

        while i < entries.length
          if entries[i].kind == :tag
            run = []
            while i < entries.length && entries[i].kind == :tag
              run << entries[i]
              i += 1
            end
            out.concat(sort_run(run, priority: priority))
          else
            out << entries[i]
            i += 1
          end
        end

        out
      end

      # Render entries back to lines.
      #
      # @param entries [Array<Entry>]
      # @return [Array<String>]
      def render(entries)
        entries.flat_map(&:lines)
      end

      # Sort one contiguous tag run.
      #
      # @param entries [Array<Entry>]
      # @param priority [Hash{String=>Integer}]
      # @return [Array<Entry>]
      def sort_run(entries, priority:)
        groups = build_groups(entries)

        groups
          .each_with_index
          .sort_by { |(group, idx)| [group_priority(group, priority), idx] }
          .map(&:first)
          .flatten
      end

      # Build sortable groups.
      #
      # A @param entry owns immediately following @option entries for the same param.
      #
      # @param entries [Array<Entry>]
      # @return [Array<Array<Entry>>]
      def build_groups(entries)
        groups = []
        i = 0

        while i < entries.length
          entry = entries[i]

          if entry.tag == 'param'
            group = [entry]
            i += 1

            while i < entries.length &&
                  entries[i].tag == 'option' &&
                  entries[i].option_owner &&
                  entries[i].option_owner == entry.subject
              group << entries[i]
              i += 1
            end

            groups << group
          else
            groups << [entry]
            i += 1
          end
        end

        groups
      end

      def group_priority(group, priority)
        priority.fetch(group.first.tag, priority.length)
      end

      def build_priority(tag_order)
        normalized_tag_order(tag_order).each_with_index.to_h
      end

      def normalized_tag_order(tag_order)
        Array(tag_order).map { |t| t.to_s.sub(/\A@/, '') }
      end

      def consume_tag_entry(lines, start_idx, index:, sortable_tags:)
        first = lines[start_idx]
        tag = extract_tag(first)

        entry_lines = [first]
        i = start_idx + 1

        while i < lines.length
          line = lines[i]
          break if sortable_top_level_tag_line?(line, sortable_tags)
          break if blank_comment_line?(line)
          break unless continuation_comment_line?(line)

          entry_lines << line
          i += 1
        end

        entry = Entry.new(
          kind: :tag,
          tag: tag,
          lines: entry_lines,
          subject: extract_subject(first, tag),
          option_owner: extract_option_owner(first),
          generated: false,
          index: index
        )

        [entry, i]
      end

      def extract_subject(line, tag)
        case tag
        when 'param'
          extract_param_name(line)
        end
      end

      # Supports:
      #   # @param [Type] name desc
      #   # @param name [Type] desc
      def extract_param_name(line)
        return Regexp.last_match(1) if line =~ /^\s*#\s*@param\b\s+\[[^\]]+\]\s+(\S+)/
        return Regexp.last_match(1) if line =~ /^\s*#\s*@param\b\s+(\S+)\s+\[[^\]]+\]/

        nil
      end

      # Supports:
      #   # @option opts [String] :foo desc
      def extract_option_owner(line)
        line[/^\s*#\s*@option\b\s+(\S+)/, 1]
      end

      def sortable_top_level_tag_line?(line, sortable_tags)
        return false unless top_level_tag_line?(line)

        sortable_tags.include?(extract_tag(line))
      end

      def extract_tag(line)
        line[/^\s*#\s*@(\w+)/, 1]
      end

      def top_level_tag_line?(line)
        !!(line =~ /^\s*#\s*@\w+/)
      end

      def comment_line?(line)
        !!(line =~ /^\s*#/)
      end

      def blank_comment_line?(line)
        !!(line =~ /^\s*#\s*$/)
      end

      def continuation_comment_line?(line)
        !!(line =~ /^\s*#[ \t]{2,}\S/)
      end
    end
  end
end
