module Docscribe
  module Infer
    FALLBACK_TYPE: "Object"

    DEFAULT_ERROR: "StandardError"

    LITERAL_TYPE_MAP: { int: "Integer", float: "Float", str: "String", dstr: "String", sym: "Symbol", true: "Boolean", false: "Boolean", nil: "nil", array: "Array", hash: "Hash", regexp: "Regexp" }
  end
end
