# frozen_string_literal: true

source 'https://rubygems.org'

gem 'docscribe', path: '..'

if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('3.2')
  group :rbs do
    gem 'rbs', require: false
  end
end
