module Docscribe
  module Plugin
    def self.run_tag_plugins: (Plugin::Context context) -> Array[Plugin::Tag]

    def self.run_collector_plugins: (Parser::AST::Node ast, Parser::Source::Buffer buffer) -> Array[Hash[Symbol, Object]]

    def self.process_single_plugin_result: (Plugin::Registry::Entry entry, Parser::AST::Node ast, Parser::Source::Buffer buffer) -> Array[Hash[Symbol, Object]]

    def self.process_plugin_insertions: (Array[Hash[Symbol, Object]] results, Plugin::Registry::Entry entry, untyped plugin) -> Array[Hash[Symbol, Object]]

    def self.valid_plugin_result?: (Object insertion, untyped plugin) -> bool

    def self.debug?: () -> bool
  end
end
