module Docscribe
  module Types
    module RBS
      module TypeFormatter
        type rbs_type = ::RBS::Types::Bases::Base
                      | ::RBS::Types::Variable
                      | ::RBS::Types::ClassSingleton
                      | ::RBS::Types::Interface
                      | ::RBS::Types::ClassInstance
                      | ::RBS::Types::Alias
                      | ::RBS::Types::Tuple
                      | ::RBS::Types::Record
                      | ::RBS::Types::Optional
                      | ::RBS::Types::Union
                      | ::RBS::Types::Intersection
                      | ::RBS::Types::Proc
                      | ::RBS::Types::Literal

        type named_rbs_type = ::RBS::Types::ClassInstance
                            | ::RBS::Types::ClassSingleton
                            | ::RBS::Types::Interface
                            | ::RBS::Types::Alias

        type formatter_fn = ^(rbs_type, ?cg: bool, ?cog: bool) -> String

        @to_yard_formatters: Hash[Class, formatter_fn]

        @named_type_classes: Array[Class]

        def self?.to_yard_formatters: () -> Hash[Class, formatter_fn]

        def self?.format_any: () -> "Object"

        def self?.format_bool: () -> "Boolean"

        def self?.format_void: () -> "void"

        def self?.format_nil: () -> "nil"

        def self?.format_optional: (::RBS::Types::Optional type, collapse_generics: bool, collapse_object_generics: bool) -> String

        def self?.format_literal: (::RBS::Types::Literal lit) -> String

        def self?.format_proc: () -> "Proc"

        def self?.format_tuple: (::RBS::Types::Tuple type, collapse_generics: bool, collapse_object_generics: bool) -> String

        def self?.format_top: () -> "Object"

        def self?.format_bottom: () -> "Object"

        def self?.format_self: () -> "self"

        def self?.format_instance: () -> "Object"

        def self?.format_class_type: () -> "Class"

        def self?.format_variable: (::RBS::Types::Variable type) -> String

        def self?.format_record: (::RBS::Types::Record type, collapse_generics: bool, collapse_object_generics: bool) -> String

        def self?.format_intersection: (::RBS::Types::Intersection type, collapse_generics: bool, collapse_object_generics: bool) -> String

        def self?.format_union: (::RBS::Types::Union type, collapse_generics: bool, collapse_object_generics: bool) -> String

        def self?.format_named: (named_rbs_type type, collapse_generics: bool, collapse_object_generics: bool) -> String

        def self?.literal_to_yard: (top lit) -> String

        def self?.to_yard: ((rbs_type | nil) type, ?collapse_generics: bool, ?collapse_object_generics: bool) -> String

        def self?.named_type?: (rbs_type type) -> bool

        def self?.named_type_classes: () -> Array[Class]

        def self?.fallback_string: (rbs_type type) -> String

        def self?.formatter_pairs: () -> untyped
      end
    end
  end
end
