module Docscribe
  class Config
    @sorbet_rbi_provider: (Types::Sorbet::RBIProvider | nil)

    def signature_provider_for: (source: String, file: String) -> (Types::ProviderChain | nil)

    def append_sorbet_providers: (Array[untyped] providers, source: String, file: String) -> void

    def sorbet_source_provider: (String source, String file) -> (Types::Sorbet::SourceProvider | nil)

    def build_provider_chain: (Array[untyped] providers) -> (Types::ProviderChain | nil)

    def sorbet_rbi_provider: () -> (Types::Sorbet::RBIProvider | nil)

    def sorbet_enabled?: () -> bool

    def sorbet_rbi_dirs: () -> Array[String]

    def sorbet_collapse_generics?: () -> bool

    def sorbet_collapse_object_generics?: () -> bool
  end
end
