module Docscribe
  module Types
    module Yard
      class Named
        def initialize: (name: String) -> void
        def name: () -> String
      end

      class Generic
        def initialize: (base: String, args: Array[untyped]) -> void
        def base: () -> String
        def args: () -> Array[untyped]
      end

      class Union
        def initialize: (types: Array[untyped]) -> void
        def types: () -> Array[untyped]
      end

      class Intersection
        def initialize: (types: Array[untyped]) -> void
        def types: () -> Array[untyped]
      end

      class Optional
        def initialize: (type: untyped) -> void
        def type: () -> untyped
      end

      class Tuple
        def initialize: (types: Array[untyped]) -> void
        def types: () -> Array[untyped]
      end

      class HashMap
        def initialize: (key_type: untyped, value_type: untyped) -> void
        def key_type: () -> untyped
        def value_type: () -> untyped
      end

      class Duck
        def initialize: (method_names: Array[String]) -> void
        def method_names: () -> Array[String]
      end

      class Literal
        def initialize: (value: String) -> void
        def value: () -> String
      end
    end
  end
end
