#!/usr/bin/env ruby

# frozen_string_literal: true

require 'optparse'
require 'stingray_docs_internal/inline_rewriter'

options = {
  stdin: false,
  write: false, # rewrite files in place
  check: false # exits 1 if any file would change
}

parser = OptionParser.new do |opts|
  opts.banner = 'Usage: stingray_docs [options] [files...]'
  opts.on('--stdin', 'Read code from STDIN and print with docs inserted') { options[:stdin] = true }
  opts.on('--write', 'Rewrite files in place (inline mode)') { options[:write] = true }
  opts.on('--check', 'Dry-run: exit 1 if any file would change') { options[:check] = true }
  opts.on('--debug', 'Enable inline debug logs') { ENV['DEBUG_INLINE'] = '1' }
  opts.on('--version', 'Print version and exit') do
    require 'stingray_docs_internal/version'
    puts StingrayDocsInternal::VERSION
    exit
  end
  opts.on('-h', '--help', 'Show this help') { puts opts; exit }
end

parser.parse!(ARGV)

def rewrite(code)
  StingrayDocsInternal::InlineRewriter.insert_comments(code)
end

if options[:stdin]
  code = STDIN.read
  puts rewrite(code)
  exit 0
end

if ARGV.empty?
  warn 'No input. Use --stdin or pass file paths. See --help.'
  exit 1
end

changed = false

ARGV.each do |path|
  src = File.read(path)
  out = rewrite(src)
  if options[:check]
    if out != src
      warn "Would change: #{path}"
      changed = true
    end
  elsif options[:write]
    if out != src
      File.write(path, out)
      puts "Updated: #{path}"
    end
  else
    puts out
  end
end

exit(options[:check] && changed ? 1 : 0)
