module Docscribe
  module Types
    interface _Provider
      def signature_for: (container: String, scope: Symbol, name: (Symbol | String), ?param_count: Integer?, ?param_names: Array[String]) -> (Types::MethodSignature | nil)
    end

    class ProviderChain
      @providers: Array[_Provider]

      def initialize: (*_Provider providers) -> void

      def signature_for: (container: String, scope: Symbol, name: (Symbol | String), ?param_count: Integer?, ?param_names: Array[String]) -> (Types::MethodSignature | nil)
    end
  end
end
