# frozen_string_literal: true

RSpec.describe 'CollectorPlugin method_override' do
  subject(:out) { inline(code, config: conf, strategy: :safe) }

  after { Docscribe::Plugin::Registry.clear! }

  def build_override_plugin(return_type:, param_types: {}, tags: [])
    Class.new(Docscribe::Plugin::Base::CollectorPlugin) do
      def initialize(return_type:, param_types: {}, tags: [])
        super()
        @return_type = return_type
        @param_types = param_types
        @tags = tags
      end

      def collect(ast, _buffer)
        node = find_first(ast, :defs) || find_first(ast, :def)
        return [] unless node

        [{
          anchor_node: node,
          method_override: {
            return_type: @return_type,
            param_types: @param_types,
            tags: @tags
          }
        }]
      end

      private

      def find_first(node, type)
        return nil unless node.respond_to?(:type)
        return node if node.type == type

        children = node.respond_to?(:children) ? node.children : []
        children.each do |child|
          next unless child.respond_to?(:type)

          found = find_first(child, type)
          return found if found
        end

        nil
      end
    end.new(return_type: return_type, param_types: param_types, tags: tags)
  end

  def find_first(node, type)
    return nil unless node.respond_to?(:type)
    return node if node.type == type

    children = node.respond_to?(:children) ? node.children : []
    children.each do |child|
      next unless child.respond_to?(:type)

      found = find_first(child, type)
      return found if found
    end

    nil
  end

  let(:conf) do
    Docscribe::Config.new(
      'emit' => {
        'header' => true,
        'param_tags' => true,
        'return_tag' => true,
        'include_default_message' => true
      }
    )
  end

  let(:code) do
    <<~RUBY
      class User
        def self.active(period: 30)
          where(created_at: period.days.ago..)
        end
      end
    RUBY
  end

  it 'applies method_override without replacing the method pipeline (keeps @param)' do
    plugin = build_override_plugin(return_type: 'ActiveRecord::Relation')

    Docscribe::Plugin::Registry.register(plugin, priority: 10)

    # - Header should be generated by Docscribe (emit.header: true)
    expect(out).to include('# +User.active+ -> ActiveRecord::Relation')

    # - Default message should still exist (DocBuilder pipeline)
    expect(out).to include('# Method documentation.')

    # - @param should be generated by Docscribe (emit.param_tags: true)
    expect(out).to include('# @param')
    expect(out).to include(' period')

    # - @return should reflect the override
    expect(out).to include('# @return [ActiveRecord::Relation]')
  end

  it 'picks the highest-priority method_override when multiple plugins target the same anchor' do
    low  = build_override_plugin(return_type: 'LOW')
    high = build_override_plugin(return_type: 'HIGH')

    Docscribe::Plugin::Registry.register(low, priority: 1)
    Docscribe::Plugin::Registry.register(high, priority: 2)

    expect(out).to include('# +User.active+ -> HIGH')
    expect(out).to include('# @return [HIGH]')
    expect(out).not_to include('# @return [LOW]')

    # Still should keep @param
    expect(out).to include('# @param')
    expect(out).to include(' period')
  end

  it 'uses param_types from method_override in @param tags' do
    plugin = build_override_plugin(
      return_type: 'ActiveRecord::Relation',
      param_types: { 'period' => 'Integer' }
    )

    Docscribe::Plugin::Registry.register(plugin, priority: 10)

    expect(out).to include('# @param [Integer] period')
    expect(out).to include('# @return [ActiveRecord::Relation]')
  end

  it 'appends override tags to the doc block' do
    override_tag = Docscribe::Plugin::Tag.new(name: 'since', text: '2.0')
    plugin = build_override_plugin(
      return_type: 'ActiveRecord::Relation',
      tags: [override_tag]
    )

    Docscribe::Plugin::Registry.register(plugin, priority: 10)

    expect(out).to include('# @since 2.0')
  end

  it 'accepts Hash-form tags in method_override and converts to Tag' do
    plugin = build_override_plugin(
      return_type: 'ActiveRecord::Relation',
      tags: [{ name: 'deprecated', text: 'Use .new instead' }]
    )

    Docscribe::Plugin::Registry.register(plugin, priority: 10)

    expect(out).to include('# @deprecated Use .new instead')
  end

  it 'accepts string-keyed Hash-form tags' do
    plugin = build_override_plugin(
      return_type: 'ActiveRecord::Relation',
      tags: [{ 'name' => 'since', 'text' => '3.0' }]
    )

    Docscribe::Plugin::Registry.register(plugin, priority: 10)

    expect(out).to include('# @since 3.0')
  end
end
